add_subdirectory(delta-studio)

if (TARGET delta-basic)
    set_property(TARGET delta-basic PROPERTY FOLDER "delta")
endif()
if (TARGET delta-basic-demo)
    set_property(TARGET delta-basic-demo PROPERTY FOLDER "delta")
endif()
if (TARGET delta-core)
    set_property(TARGET delta-core PROPERTY FOLDER "delta")
endif()
if (TARGET delta-physics)
    set_property(TARGET delta-physics PROPERTY FOLDER "delta")
endif()

add_subdirectory(simple-2d-constraint-solver)

if (TARGET simple-2d-constraint-solver)
    set_property(TARGET simple-2d-constraint-solver PROPERTY FOLDER "scs")
endif()
if (TARGET simple-2d-constraint-solver-test)
    set_property(TARGET simple-2d-constraint-solver-test PROPERTY FOLDER "scs")
endif()

add_subdirectory(csv-io)

if (TARGET csv-io)
    set_property(TARGET csv-io PROPERTY FOLDER "csv-io")
endif()
if (TARGET csv-io-main)
    set_property(TARGET csv-io-main PROPERTY FOLDER "csv-io")
endif()
if (TARGET csv-io-test)
    set_property(TARGET csv-io-test PROPERTY FOLDER "csv-io")
endif()

if (DTV)
    add_subdirectory(direct-to-video)

    if (TARGET direct-to-video)
        set_property(TARGET direct-to-video PROPERTY FOLDER "dtv")
    endif()
endif (DTV)

add_subdirectory(piranha)

if (TARGET piranha)
    set_property(TARGET piranha PROPERTY FOLDER "piranha")
endif()
if (TARGET piranha_test)
    set_property(TARGET piranha_test PROPERTY FOLDER "piranha")
endif()
if (TARGET piranha_reference_compiler)
    set_property(TARGET piranha_reference_compiler PROPERTY FOLDER "piranha")
endif()
